### ISSUE TITLE
Baraha

### ISSUE THREAD

**Issue by skmnktl** [indic-transliteration/common_maps#1]
Since Baraha is closely related to optitrans, should we add any deviations from optitrans as alternatives or separate it out? 

See @vvasuki 's listing [here](https://docs.google.com/spreadsheets/d/1o2vysXaXfNkFxCO-WD77C4AEbXcAcJmDVgUb-E0mYbg/edit#gid=0) for the differences between the two.

**Comment by vvasuki** [comment]
Separate it out please.
