### ISSUE TITLE
| - ळ्ह mapping in SLP1

### ISSUE THREAD

**Issue by drdhaval2785** [indic-transliteration/common_maps#12]
SLP1 has special character `|` for Vedic retroflex l.
This needs to be captured.
I am afraid to create a PR as I do not understand what all places would require change.
I would also appreciate if you can guide me the places to correct in this case.
That would give me a hands on training for future PRs.

![image](https://user-images.githubusercontent.com/5755132/135635735-4c36cecd-634d-43c7-91d0-9024099d40ee.png)

**Comment by vvasuki** [comment]
L is for retroflex l (ळ्)। 
| is for aspirated retroflex l ळ्ह्। 

No other script or scheme AFAIK has a special character for the second case - they just use the corresponding symbols for ळ् and ह् successively. So, mapping to devanAgarI or any other scheme would require Lh to be used. 

Just add a special case before https://github.com/indic-transliteration/indic_transliteration_py/blob/0551ff6e2616bdaabd017b42e0e9130ebb910e45/indic_transliteration/sanscript/__init__.py#L224 . SOmething like:

```python
if _from.startswith(roman.SLP1):
  data = data.replace("|", "Lh")
```

Also maybe:

```python
if _to.startswith(roman.SLP1):
  result = result.replace("Lh", "|")
```

**Comment by vvasuki** [comment]
Thought of and implemented a more general and elegant way of solving this. (linked above)
