### ISSUE TITLE
Error in Grantha "au"

### ISSUE THREAD

**Issue by akprasad** [indic-transliteration/common_maps#24]
I believe the Grantha "au" vowel sign should be rendered as 𑌕𑍌 , but 𑌕𑍗 is produced instead.

I don't know Grantha well, so I might be mistaken.

See https://github.com/ambuda-org/vidyut/issues/84 for details.

**Comment by vvasuki** [comment]
𑌕𑍌 looks like को । Observe 
![image](https://github.com/indic-transliteration/common_maps/assets/2664797/e234a6ee-0ef2-473b-bf4c-b9d9b7e2a759)


cc @jamadagni @virtualvinodh

**Comment by deepestblue** [comment]
Yeah, 𑌕𑍋 is irrelevant here. 𑌕𑍌 is the historically accurate form and is also similar to the forms used in the Malayalam and Tamil scripts: കൌ and கௌ respectively. Some printers have tended to abbreviate 𑌕𑍌 to just 𑌕𑍗, and as such it's considered an alternative rendering.

From a quality of implementation perspective, here are my thoughts:

* At the very least, 𑌕𑍌 and 𑌕𑍗 should both go to कौ when transliterating out of Grantha.
* A next level of support would be, If indic-transliteration supports user-options, there should be an option to pick one vs. the other from transliterating *into* Grantha.
* Selfishly :-) my default would be 𑌕𑍌 for consistency but I have no usage data to support my case.

**Comment by vvasuki** [comment]
I see, thanks -

![image](https://github.com/indic-transliteration/common_maps/assets/2664797/547a574f-0352-4bc7-a16c-5879530523fd)


So there are separate unicode numbers for these. Will add an alternate, and make the mAtra the default.
