### ISSUE TITLE
Roman transliteration of ळ

### ISSUE THREAD

**Issue by tkshnwesper** [indic-transliteration/common_maps#35]
Hi,

I've seen that the letter ळ is transliterated as `l̤` in many of the roman maps like [iast](https://github.com/indic-transliteration/common_maps/blob/master/roman/iast.toml#L84) while the [sanscript web tool](https://learnsanskrit.org/tools/sanscript/) as well as [wikipedia](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration#Inventory_and_conventions) say that it should be `ḻ`.

Which one is correct?

**Comment by vvasuki** [comment]
Fixed with https://github.com/indic-transliteration/common_maps/commit/2358c9074d7cb69e7a50a67677b39112b37d13de
